export const menu = [
  {
    id: 1,
    title: "Buttermilk Pancakes",
    category: "breakfast",
    price: "22.99",
    img: "images/img1.jpeg",
    desc: "Try our mouth-watering restaurant menu designs. ",
  },
  {
    id: 2,
    title: "Egg Attack",
    category: "lunch",
    price: "15",
    img: "images/img2.jpeg",
    desc: "Easily customize to match your brand.",
  },
  {
    id: 3,
    title: "Country Delight",
    category: "dinner",
    price: "16.3",
    img: "images/img3.jpeg",
    desc: "customized by you.Try our mouth-watering restaurant menu designs.",
  },
  {
    id: 4,
    title: "dinner double",
    category: "dinner",
    price: "18",
    img: "images/img4.jpeg",
    desc: "Make edits whenever you need. Designed by professionals.",
  },
  {
    id: 5,
    title: "Orea Dream",
    category: "dinner",
    price: "11.57",
    img: "images/img5.jpeg",
    desc: "Designed by professionals, customized by you.",
  },
  {
    id: 6,
    title: "Orea Dream2",
    category: "breakfast",
    price: "14.80",
    img: "images/img6.jpeg",
    desc: "customized whenever you need by you.",
  },
  {
    id: 7,
    title: "Orea Dream",
    category: "breakfast",
    price: "13.99",
    img: "images/img7.jpeg",
    desc: " match your brandmMake edits whenever you need.",
  },
  {
    id: 8,
    title: "Egg Attack",
    category: "breakfast",
    price: "17.16",
    img: "images/img8.jpeg",
    desc: "Try our mouth-watering restaurant menu designs.",
  },
];
